# Generated by Django 5.1.6 on 2025-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(),
        ),
    ]
