# Generated by Django 5.1.6 on 2025-03-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_course_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='Cơ bản', max_length=10),
        ),
    ]
