# Generated by Django 5.1.6 on 2025-03-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_course_level_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
