# Generated by Django 5.1.6 on 2025-03-23 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
