# Generated by Django 5.1.6 on 2025-03-23 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_course_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='level',
        ),
    ]
