# Generated by Django 5.1.6 on 2025-03-23 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_course_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='course',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
