# Generated by Django 5.1.6 on 2025-03-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='Cơ bản', max_length=10, null=True),
        ),
    ]
