# Generated by Django 5.1.6 on 2025-03-24 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api', models.CharField(max_length=10000, null=True)),
            ],
        ),
    ]
