# Generated by Django 5.1.6 on 2025-03-24 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_googleapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAPI_Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_api_key', models.CharField(max_length=100000)),
            ],
        ),
        migrations.DeleteModel(
            name='GoogleAPI',
        ),
    ]
