# Generated by Django 5.1.6 on 2025-03-24 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_googleapi_key_delete_googleapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GoogleAPI_Key',
            new_name='Google_API_Key',
        ),
    ]
