# Generated by Django 5.1.6 on 2025-03-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_delete_google_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ielts_course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='thptqg_course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='toeic_course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='', max_length=10, null=True),
        ),
    ]
