# Generated by Django 5.1.6 on 2025-03-24 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_alter_course_level_alter_ielts_course_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
