# Generated by Django 5.1.6 on 2025-03-24 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.course'),
        ),
    ]
