# Generated by Django 5.1.6 on 2025-03-24 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_orderitem_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='quality',
        ),
    ]
