# Generated by Django 5.1.6 on 2025-03-24 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_remove_orderitem_quality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
