# Generated by Django 5.1.6 on 2025-03-24 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_alter_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.ImageField(blank=True, default=0, null=True, upload_to=''),
        ),
    ]
