# Generated by Django 5.1.6 on 2025-03-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='ielts_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ielts_course'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='thptqg_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.thptqg_course'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='toeic_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.toeic_course'),
        ),
    ]
