# Generated by Django 5.1.6 on 2025-03-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_remove_orderitem_ielts_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_type',
        ),
    ]
