# Generated by Django 5.1.6 on 2025-03-25 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_order_customer_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IELTS_Course',
        ),
        migrations.DeleteModel(
            name='THPTQG_Course',
        ),
        migrations.DeleteModel(
            name='TOEIC_Course',
        ),
    ]
