# Generated by Django 5.1.6 on 2025-03-25 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_delete_ielts_course_delete_thptqg_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tai_lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10000, null=True)),
                ('content', models.TextField(max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
