# Generated by Django 5.1.6 on 2025-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_tai_lieu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tai_lieu',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='tai_lieu/'),
        ),
    ]
