# Generated by Django 5.1.6 on 2025-03-26 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_tai_lieu_file_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tai_lieu',
            name='file_upload',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='tai_lieu/'),
        ),
    ]
