# Generated by Django 5.1.6 on 2025-03-26 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_alter_tai_lieu_file_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tai_lieu',
            old_name='header',
            new_name='name',
        ),
    ]
