# Generated by Django 5.1.6 on 2025-03-26 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_rename_header_tai_lieu_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='De_thi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('level', models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='', max_length=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_upload', models.FileField(blank=True, max_length=250, null=True, upload_to='de_thi/')),
            ],
        ),
    ]
