# Generated by Django 5.1.6 on 2025-03-27 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0057_de_thi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000, null=True)),
                ('price', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('evaluate', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
