# Generated by Django 5.1.6 on 2025-03-27 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0058_sach'),
    ]

    operations = [
        migrations.AddField(
            model_name='sach',
            name='author',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='sach',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
