# Generated by Django 5.1.6 on 2025-03-27 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_sach_author_sach_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sach'),
        ),
    ]
