# Generated by Django 5.1.6 on 2025-03-27 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_orderitem_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='book',
        ),
    ]
