# Generated by Django 5.1.6 on 2025-03-27 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_orderitembook'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItemBook',
            new_name='BookOrderItem',
        ),
    ]
