# Generated by Django 5.1.6 on 2025-03-27 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_rename_orderitembook_bookorderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard_Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_csv', models.FileField(blank=True, max_length=250, null=True, upload_to='flash_card/')),
            ],
        ),
    ]
