# Generated by Django 5.1.6 on 2025-03-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_vinh_danh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vinh_danh',
            name='file_csv',
            field=models.FileField(blank=True, max_length=250, null=True, upload_to='vinh_danh/'),
        ),
    ]
