# Generated by Django 5.1.6 on 2025-05-22 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_alter_vinh_danh_file_csv'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Nội dung câu hỏi')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Thứ tự')),
            ],
            options={
                'verbose_name': 'Câu Hỏi',
                'verbose_name_plural': 'Các Câu Hỏi',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tiêu đề bài test')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
                ('time_limit_minutes', models.PositiveIntegerField(default=30, verbose_name='Thời gian làm bài (phút)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Bài Test',
                'verbose_name_plural': 'Các Bài Test',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Nội dung lựa chọn')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Là đáp án đúng')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='app.question', verbose_name='Câu Hỏi')),
            ],
            options={
                'verbose_name': 'Lựa Chọn',
                'verbose_name_plural': 'Các Lựa Chọn',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='app.test', verbose_name='Bài Test'),
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian bắt đầu')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Thời gian kết thúc')),
                ('score', models.FloatField(blank=True, null=True, verbose_name='Điểm số')),
                ('completed', models.BooleanField(default=False, verbose_name='Hoàn thành')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.test', verbose_name='Bài Test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người dùng')),
            ],
            options={
                'verbose_name': 'Lần Làm Test',
                'verbose_name_plural': 'Các Lần Làm Test',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.testattempt', verbose_name='Lần làm test')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.question', verbose_name='Câu Hỏi')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.choice', verbose_name='Lựa chọn đã chọn')),
            ],
            options={
                'verbose_name': 'Câu Trả Lời Của Người Dùng',
                'verbose_name_plural': 'Các Câu Trả Lời Của Người Dùng',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
