# Generated by Django 5.1.6 on 2025-05-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0067_question_test_choice_question_test_testattempt_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id'], 'verbose_name': 'Lựa Chọn', 'verbose_name_plural': 'Các Lựa Chọn'},
        ),
    ]
