# Generated by Django 5.1.6 on 2025-05-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_alter_testattempt_total_questions_at_submission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testattempt',
            name='correct_answers_count',
        ),
        migrations.RemoveField(
            model_name='testattempt',
            name='total_questions_at_submission',
        ),
    ]
