# Generated by Django 5.2.1 on 2025-05-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0072_testattempt_correct_answers_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text="Ví dụ: '3 tháng', '20 giờ', '6 tuần'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='Link video giới thiệu khóa học (ví dụ: YouTube, Vimeo)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='course_images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('Cơ bản', 'Cơ bản'), ('Trung bình', 'Trung bình'), ('Nâng cao', 'Nâng cao')], default='Cơ bản', max_length=10, null=True),
        ),
    ]
