name: Django CI/CD

on:
  push:
    branches:
      - master # Kích hoạt workflow khi có push lên nhánh 'main'
  pull_request:
    branches:
      - master # Chạy workflow khi có pull request đến nhánh 'main'

jobs:
  build:
    runs-on: ubuntu-latest # Chạy job trên runner Ubuntu mới nhất

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Kéo mã nguồn từ repository

      - name: Set up Python
        uses: actions/setup-python@v5 # Thiết lập môi trường Python
        with:
          python-version: '3.9' # Chọn phiên bản Python bạn muốn sử dụng (ví dụ: 3.8, 3.9, 3.10, 3.11)

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Cài đặt các gói từ requirements.txt

      - name: Run Django migrations (optional, for testing with a real DB)
        # Bước này thường chỉ thực hiện trong môi trường test hoặc staging.
        # Trong môi trường production, bạn có thể chạy migrate như một bước riêng.
        run: python manage.py migrate --noinput
        env:
          DJANGO_SETTINGS_MODULE: english_web.settings # Thay your_project_name bằng tên project Django của bạn
          DATABASE_URL: sqlite:///db.sqlite3 # Ví dụ dùng SQLite cho test. Thay đổi nếu bạn dùng DB khác.

      - name: Run Django tests
        run: python manage.py test # Chạy các bài kiểm thử của Django
        env:
          DJANGO_SETTINGS_MODULE: english_web.settings # Thay your_project_name bằng tên project Django của bạn
          DATABASE_URL: sqlite:///db.sqlite3 # Đảm bảo DB config cho test

      # --- Các bước triển khai (Deployment) - Tùy chọn ---
      # Các bước này sẽ thay đổi rất nhiều tùy thuộc vào nơi bạn muốn triển khai ứng dụng.
      # Dưới đây là một ví dụ điển hình cho việc xây dựng và đẩy Docker image.

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' # Chỉ chạy nếu là push lên nhánh main

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          username: ${{ secrets.DOCKER_USERNAME }} # GitHub Secret cho Docker Hub username
          password: ${{ secrets.DOCKER_PASSWORD }} # GitHub Secret cho Docker Hub password

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        with:
          context: . # Đường dẫn đến Dockerfile của bạn (nếu ở thư mục gốc)
          file: ./Dockerfile # Đường dẫn đến Dockerfile của bạn
          push: true
          tags: |
            your-dockerhub-username/your-django-app:latest # Thay bằng tên người dùng Docker Hub và tên repo của bạn
            your-dockerhub-username/your-django-app:${{ github.sha }} # Tag với SHA của commit

      # --- Ví dụ triển khai lên SSH/Server (nếu không dùng Docker cho deployment) ---
      # - name: Deploy via SSH
      #   uses: appleboy/ssh-action@master
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USERNAME }}
      #     key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     script: |
      #       cd /path/to/your/django/project
      #       git pull origin main
      #       pip install -r requirements.txt
      #       python manage.py migrate
      #       # Restart Gunicorn/Apache/Nginx service
      #       sudo systemctl restart gunicorn your_django_app
      #       sudo systemctl restart nginx